# Generated by Django 5.1.1 on 2024-10-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_create_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_task',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
