# Generated by Django 5.1.1 on 2024-10-09 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0005_assign_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assign_task',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_assigned_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assign_task',
            name='assign_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
