# Generated by Django 5.1.1 on 2024-10-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0006_assign_task_assigned_by_alter_assign_task_assign_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign_task',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assign_task',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
