# Generated by Django 5.1.1 on 2024-10-09 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0007_assign_task_is_completed_assign_task_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assign_task',
            name='is_deleted',
        ),
    ]
