# Generated by Django 5.1.1 on 2024-10-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0010_alter_create_task_clear_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_task',
            name='clear_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
