# Generated by Django 5.1.1 on 2024-10-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0012_alter_create_task_clear_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_task',
            name='clear_datetime',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
