# Generated by Django 5.1.1 on 2024-10-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0013_alter_create_task_clear_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign_task',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('On Hold', 'On Hold')], default='Not Started', max_length=50),
        ),
    ]
