# Generated by Django 5.1.1 on 2024-10-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0014_assign_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign_task',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
